version: "3.9"

services:
  zookeeper:
    image: zookeeper
    
    expose:
      - "2181"

    volumes:
      - ./zookeeper/conf:/conf


  kafka:
    image: wurstmeister/kafka

    expose:
      - "9092"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    environment:
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 369295700
      KAFKA_BROKER_ID: 1
      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_HOST_NAME: kafka
      
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CREATE_TOPICS: "swjudge-submit:1:1,\
                            swjudge-result:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

      KAFKA_HEAP_OPTS: "-Xms2g -Xmx6g"

    depends_on:
      - zookeeper


  judger-api:
    build:
      context: ./judger-backend/judger-api
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-backend/judger-api/.env

    ports:
      - "9001:4003"
    
    volumes:
      - ./judger-backend/judger-api/uploads:/usr/src/app/uploads
      - ./judger-backend/judger-api/server-Logs:/usr/src/app/logs
      - ./judger-backend/judger-api:/usr/src/app
      - /usr/src/app/node_modules

    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb


  judger:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-backend/judger/.env

    volumes:
      - ./judger-backend/judger/uploads:/source
      - ./judger-backend/judger/uploads:/io
      - ./judger-backend/judger:/app
      - /app/node_modules
    
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb


  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev

    ports:
     - "9000:4000"
    
    volumes:
     - ./auth/server-Logs:/usr/src/app/logs
     - ./auth:/usr/src/app
     - /usr/src/app/node_modules

    depends_on:
      - mongodb
    links:
      - mongodb


  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    
    ports:
      - "27017:27017"

    volumes:
      - ./mongo/mongodb:/data/db