version: "3.8"

services:
  zookeeper:
    image: zookeeper
    volumes:
      - ./zookeeper/conf:/conf
    expose:
      - "2181"
      - "2888"
      - "3888"

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 369295700
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_HEAP_OPTS: "-Xms4g -Xmx8g"
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "swjudge-submit:1:1, swjudge-result:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "9092"
    depends_on:
      - zookeeper

  judger:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-backend/judger/.env
    volumes:
      - ./judger-backend/judger/Uploads:/source
      - ./judger-backend/judger:/app
      - /app/node_modules
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger-api:
    build:
      context: ./judger-backend/judger-api
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-backend/judger-api/.env
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb
    ports:
      - "9001:4003"
    volumes:
      - ./judger-backend/judger-api:/usr/src/app
      - ./judger-backend/judger-api/Uploads:/usr/src/app/uploads
      - ./judger-backend/judger-api/server-Logs:/usr/src/app/logs
      - /usr/src/app/node_modules

  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - ./mongo/mongodb:/data/db
    expose:
      - "27017"