version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/conf:/conf

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 369295700
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_HEAP_OPTS: "-Xms6g -Xmx8g"
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "swjudge-submit:6:1,swjudge-result:6:1"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  judger1:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger2:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger3:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger4:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger5:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger6:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger7:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger8:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger-api:
    build:
      context: ./judger-api
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    ports:
      - "4003:4003"
    depends_on:
      - mongodb
      - kafka
    links:
      - mongodb
      - kafka
    volumes:
      - ./Server-Logs:/usr/src/app/logs
      - ./Uploads:/usr/src/app/uploads
      - ./judger-api:/usr/src/app

  judger-web:
    build:
      context: ./judger-web
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./judger-web:/app

  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
