version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/conf:/conf

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 369295700
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_HEAP_OPTS: "-Xms4g -Xmx6g"
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS:
        "swjudge-submit:4:1,\
         swjudge-result:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper


  judger1:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - ./judger/.env
    volumes:
      - ./Uploads:/source
      - ./Uploads:/io
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger2:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - ./judger/.env2
    volumes:
      - ./Uploads:/source
      - ./Uploads:/io
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger3:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - ./judger/.env3
    volumes:
      - ./Uploads:/source
      - ./Uploads:/io
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger4:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - ./judger/.env4
    volumes:
      - ./Uploads:/source
      - ./Uploads:/io
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger5:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - ./judger/.env4
    volumes:
      - ./Uploads:/source
      - ./Uploads:/io
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  judger-api:
    build:
      context: ./judger-api
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-api/.env
    ports:
      - "4003:4003"
    depends_on:
      - mongodb
      - kafka
    links:
      - mongodb
      - kafka
    volumes:
      - ./Server-Logs:/usr/src/app/logs
      - ./Uploads:/usr/src/app/uploads

  judger-web:
    build:
      context: ./judger-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
