version: "3.8"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/conf:/conf

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 369295700
      KAFKA_HEAP_OPTS: "-Xms4g -Xmx6g"
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS:
        "swjudge-submit:1:1,\
         swjudge-result:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  judger1:
    build:
      context: ./judger
      dockerfile: Dockerfile.dev
    env_file:
      - judger/.env
    volumes:
      - ./Uploads:/source
      - ./judger:/app
    depends_on:
      - kafka
      - mongodb
    links:
      - kafka
      - mongodb

  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
