version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/conf:/conf

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 369295700
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_HEAP_OPTS: "-Xms8g -Xmx16g"
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "swjudge-submit:6:1,swjudge-result:6:1"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  judger1:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - judger/.env
    volumes:
      - /uploads:/source
      - /uploads:/io
    depends_on:
      - kafka

    links:
      - kafka


  judger2:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - judger/.env
    volumes:
      - /uploads:/source
      - /uploads:/io
    depends_on:
      - kafka

    links:
      - kafka


  judger3:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - judger/.env
    volumes:
      - /uploads:/source
      - /uploads:/io
    depends_on:
      - kafka

    links:
      - kafka


  judger4:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - judger/.env
    volumes:
      - /uploads:/source
      - /uploads:/io
    depends_on:
      - kafka

    links:
      - kafka


  judger5:
    build:
      context: ./judger
      dockerfile: Dockerfile
    env_file:
      - judger/.env
    volumes:
      - /uploads:/source
      - /uploads:/io
    depends_on:
      - kafka

    links:
      - kafka


  judger-api:
    build:
      context: ./judger-api
      dockerfile: Dockerfile
    env_file:
      - ./judger-api/.env
    ports:
      - "4003:4003"
    depends_on:

      - kafka
    links:

      - kafka
    volumes:
      - /server-Logs:/usr/src/app/logs
      - /uploads:/usr/src/app/uploads

  judger-web:
    build:
      context: ./judger-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./judger-web/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - judger-api
    links:
      - judger-api
